{% set name = "pyjs_code_runner" %}
{% set version = "1.1.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/emscripten-forge/pyjs-code-runner/archive/{{ version }}.tar.gz
  sha256: 0c9a6cc462ee2ee28d7944bdd8a6954ff187bd243b7ac048ef4e29f6bcdc3bd7

build:
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv


requirements:
  host:
    - python
    - pip
  run:
    - python
    - empack >=2.0
    - rich
    - typer
    - appdirs

test:
  imports:
    - pyjs_code_runner

about:
  home: https://github.com/emscripten-forge/pyjs-code-runner
  summary: 'A tool to run emscripten-forge compiled python-wasm code from the terminal'
  description: |
    A tool to run emscripten-forge compiled python-wasm code from the terminal
  license: MIT
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - DerThorsten
