{% set name = "pyjs_code_runner" %}
{% set version = "3.1.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/emscripten-forge/pyjs-code-runner/archive/{{ version }}.tar.gz
  sha256: 76e603cc9fca872e68260639c08f11172edfefc332ecaeb495da05b9b5ed60e8

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv


requirements:
  build:
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - python                              # [build_platform != target_platform]
    - pip                                 # [build_platform != target_platform]
    - hatchling                           # [build_platform != target_platform]
  host:
    - python
    - pip
    - hatchling
  run:
    - python
    - empack >=3.0
    - rich
    - typer
    - appdirs

test:
  imports:
    - pyjs_code_runner

about:
  home: https://github.com/emscripten-forge/pyjs-code-runner
  summary: A tool to run emscripten-forge compiled python-wasm code from the terminal
  description: |
    A tool to run emscripten-forge compiled python-wasm code from the terminal
  license: MIT
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - DerThorsten
