{% set name = "pyjs_code_runner" %}
{% set version = "2.0.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/emscripten-forge/pyjs-code-runner/archive/{{ version }}.tar.gz
  sha256: 0f6c9ad2e26e4c8a2bce8e7ac662ed309de41e1cc7e7bc0d56587764d983686e

build:
  number: 3
  script: {{ PYTHON }} -m pip install . --no-deps -vv


requirements:
  build:
    - python                              # [build_platform != target_platform]
    - pip                                 # [build_platform != target_platform]
  host:
    - python
    - pip
  run:
    - python
    - empack >=3.0
    - rich
    - typer
    - appdirs

test:
  imports:
    - pyjs_code_runner

about:
  home: https://github.com/emscripten-forge/pyjs-code-runner
  summary: A tool to run emscripten-forge compiled python-wasm code from the terminal
  description: |
    A tool to run emscripten-forge compiled python-wasm code from the terminal
  license: MIT
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - DerThorsten
